// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {datasets} from '../models';

export function LoadDataset(arg1:boolean):Promise<datasets.DatasetInfo>;
