// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadDataset(arg1) {
  return window['go']['main']['App']['LoadDataset'](arg1);
}
